name: build_package_rock5

on: 
  push:
    paths-ignore:
      - 'LICENSE'

jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-22.04
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - name: test
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV    

      - name: Clean UP
        run: |
          sudo rm -Rf *
     
      - name: Git clone
        run: |
          git clone https://github.com/OpenHD/ChrootCompilationTest /opt/ChrootCompilationTest
      
      - name: Write API key to file
        run: |
          echo $CLOUDSMITH_API_KEY > /opt/ChrootCompilationTest/additionalFiles/cloudsmith_api_key.txt

      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Install Repository
        run: |
          ls -a
          echo "show if key was written"
          ls -a /opt/ChrootCompilationTest/additionalFiles/
          mv ../OpenHD /opt/ChrootCompilationTest/additionalFiles/
          cd /opt/ChrootCompilationTest/
          sudo bash install_dep.sh
          sudo bash build.sh rock5
