name: build_package_rock5

on: 
  push:
    paths-ignore:
      - 'LICENSE'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-22.04
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - name: test
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV    

      - name: Clean UP
        run: |
          sudo rm -Rf *
              
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Repository
        run: |
          git clone https://github.com/OpenHD/ChrootCompilationTest /opt/ChrootCompilationTest
          mkdir -p /opt/ChrootCompilationTest/additionalFiles
          mv OpenHD /opt/ChrootCompilationTest/additionalFiles/
          cd /opt/ChrootCompilationTest/
          sudo bash install_dep.sh
          sudo bash build.sh rock5 openhd
      - name: Upload to Github
        uses: 'actions/upload-artifact@v2'
        with:
          name: "OpenHD"
          path: |
            *.deb
            *.log
          if-no-files-found: error

      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "openhd-2-3-evo"
          distro: "ubuntu"
          release: "jammy"
          republish: "true" # needed ONLY if version is not changing
          file: "*.deb"
