name: Build Jetson

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: test
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV    

      - name: Clean UP
        run: |
          sudo rm -Rf *

      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Install Dependencies
        run: |
          sudo ./install_dep_jetson.sh

      - name: Build with make
        run: |
          sudo mkdir -p /usr/local/share/openhd/
          sudo touch /usr/local/share/openhd/joyconfig.txt
          sudo chmod +x install_dep_jetson.sh
          sudo ./install_dep_jetson.sh
          sudo ./package.sh armhf raspbian bullseye
          ls -a

      - name: Upload to Github
        uses: 'actions/upload-artifact@v2'
        with:
          name: "Open.HD"
          path: |
            *.deb
            *.log
          if-no-files-found: error
    
      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "openhd-2-1-alpha"
          distro: "ubuntu"
          release: "bionic"
          republish: "true" # needed ONLY if version is not changing
          file: "Open.HD/*.deb"
          
      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
