name: Build Jetson ONLINE

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "Hello World"

      - name: Emulating Jetson
        id: push
        uses: pguyot/arm-runner-action@f204b58258d5b01e297eec6db036a14b11dc9ffa
        with:
          base_image: https://developer.download.nvidia.com/embedded/L4T/r32_Release_v6.1/Jetson_Nano_2GB/jetson-nano-2gb-jp46-sd-card-image.zip
          cpu: cortex-a53
          bootpartition:
          rootpartition: 1
          commands: |
            cat /etc/os-release
            uname -a
            ifconfig -a


