name: Build Jetson ONLINE

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "Hello World"

      - name: Emulating Jetson
        id: qemu
        uses: pguyot/arm-runner-action@284a45c9d5983239745b7ceba40187cc81d316e4
        with:
          base_image: https://developer.download.nvidia.com/embedded/L4T/r32_Release_v6.1/Jetson_Nano_2GB/jetson-nano-2gb-jp46-sd-card-image.zip
          cpu: cortex-a53
          bootpartition:
          rootpartition: 1
          image_additional_mb: 4000
          copy_repository_path: /opt
          copy_artifact_path: Open.HD
          import_github_env: true
          commands: |
            ls -a
            cd /opt
            cd Open.HD
            rm /etc/apt/sources.list.d/nvidia-l4t-apt-source.list || true
            echo "deb https://repo.download.nvidia.com/jetson/common r32.6 main" > /etc/apt/sources.list.d/nvidia-l4t-apt-source2.list
            echo "deb https://repo.download.nvidia.com/jetson/t210 r32.6 main" > /etc/apt/sources.list.d/nvidia-l4t-apt-source.list
            sudo cat /etc/apt/sources.list.d/nvidia-l4t-apt-source.list
            apt update
            apt upgrade -y
            mkdir -p /usr/local/share/openhd/
            touch /usr/local/share/openhd/joyconfig.txt
            ls -a  
            sudo chmod +x install_dep_jetson.sh 
            sudo ./install_dep_jetson.sh
            sudo ./package.sh arm64 ubuntu bionic


      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "openhd-2-1-alpha"
          distro: "ubuntu"
          release: "bionic"
          republish: "true" # needed ONLY if version is not changing
          file: "Open.HD/*.deb"
