name: Build Jetson ONLINE

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "Hello World"

      - name: Push
        id: push
          uses: pguyot/arm-runner-action@v2
          with:
            base_image: https://developer.nvidia.com/embedded/l4t/r32_release_v7.1/jp_4.6.1_b110_sd_card/jetson_xavier_nx/jetson-nx-jp461-sd-card-image.zip
            cpu: cortex-a53
            bootpartition:
            rootpartition: 1
            commands: |
              cat /etc/os-release
              uname -a


