name: Build RPI

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: pguyot/arm-runner-action@v2.3.1 
      id: build_image
      with:
        base_image: raspios_lite:latest
        commands: |

    - name: Clean UP
      run: |
        sudo rm -Rf *

    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
          
    - name: Install Dependencies
      run: |
        sudo ./install_dep.sh

    - name: Build with make
      run: |
        sudo ./package.sh armhf raspbian bullseye

    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "Open.HD"
        path: |
          *.deb
          *.log
        if-no-files-found: error
          
      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
