name: Build RPI

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: test
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV    

      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Install Dependencies
        run: |
          sudo ./install_dep.sh

      - name: Build with make
        run: |
          ./package.sh

      - name: Show files
        run: |
          tree

          
      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
