name: Build RPI

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
    - uses: pguyot/arm-runner-action@v2.3.1 
      id: build_image
      with:
        base_image: raspios_lite:latest
        image_additional_mb: 40000
        commands: |
            apt install git
            git clone --recursive https://github.com/OpenHD/Open.HD
            cd Open.HD
            git checkout consti-builder
            sudo ./install_dep.sh
            sudo ./package.sh armhf raspbian bullseye

    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "Open.HD"
        path: |
          *.deb
          *.log
        if-no-files-found: error
          
      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
