name: Build RPI

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: self-hosted
    steps:
 - shell: bash
    env:
      SUPER_SECRET: ${{ secrets.CLOUDSMITH_API_KEY }}
    run: |
      echo "$SUPER_SECRET"