name: UbuntuX86BuildTest

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - name: test
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV    

      - name: Clean UP
        run: |
          sudo rm -Rf *

      - name: Install cloudsmith
        run: |
          sudo apt update
          sudo apt install python3-pip
          pip3 install --upgrade cloudsmith-cli
          curl -H "X-Api-Key: ${{ secrets.CLOUDSMITH_API_KEY }}" https://api.cloudsmith.io/user/self/
                

      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
         sudo chmod +x install_dep_x86.sh
         sudo ./install_dep_x86.sh

      - name: Build with make
        run: |
          curl -H "X-Api-Key: ${{ secrets.CLOUDSMITH_API_KEY }}" https://api.cloudsmith.io/user/self/
          sudo ./package.sh x86 ubuntu bionic

      - name: Upload to Github
        uses: 'actions/upload-artifact@v2'
        with:
          name: "Open.HD"
          path: |
            *.deb
            *.log
          if-no-files-found: error